### ISSUE TITLE
Готовий допомагати проекту

### ISSUE THREAD

**Issue by dmytrohridin** [matrunchyk/ua.vuejs.org#1]
**Готовий долучитись до перекладу**
Цікавить чи є наразі сформований список, що потрібно перекласти, пріоритети і т.д.
Дякую

**Comment by tarasyyyk** [comment]
Список тут https://github.com/vuejs/vuejs.org/issues/2015#issuecomment-544188398



> Готовий долучитись до перекладу

**+1**

**Comment by matrunchyk** [comment]
@dmytrohridin @tarasyyyk Перепрошую за затримку у відповіді, лише помітив цей тред (несподівано для себе). 

Пропоную для швидкої комунікації [ось цей Телеграм канал](https://t.me/vuejs_ukraine).
