### ISSUE TITLE
Wanna help with translation to RU docs

### ISSUE THREAD

**Issue by andypike7** [matrunchyk/ua.vuejs.org#3]
Привет.

Я скачал репозитории:
https://github.com/vuejs/vuejs.org.git
https://github.com/translation-gang/ru.vuejs.org

Но во втором всё уже переведено.
Как начать?
Из первого петерянуть страницы, которых нет во втором, перевести и за пуллреквестить?

**Comment by andypike7** [comment]
Протолкнул Vue к нам, в Rеcall Masters Inc, плотно работал год.
Но у них сокращения, понятно из-за чего, я попал.
Хотел бы внести вклад, свободен, т.к. ищу работу.
Да и потом тоже хочу вносить вклад в популяризацию Vue.

**Comment by matrunchyk** [comment]
@andypike7 RU → https://github.com/vuejs/vuejs.org#russian
